import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import LogoutButton from '@/components/button/LogoutButton';
import Providers from '@/store/queryProvider';

import Header from '@/components/layout/Header';
import { createClient } from '@/utils/supabase/server';
import { UserStoreProvider } from '@/providers/userStoreProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {
    data: { user }
  } = await createClient().auth.getUser();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <UserStoreProvider isUser={!!user}>
            <Header />
            {children}
          </UserStoreProvider>
        </Providers>
      </body>
    </html>
  );
}
